Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Web.MVC.ComercioDigital.Models
{
    public class Pedido
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo Título é obrigatório.")]
        public string Titulo { get; set; }
        public int Numero { get; set; }

        [Required(ErrorMessage = "O campo Título é obrigatório.")]
        public Guid ClienteId { get; set; }
        public string NomeCliente { get; set; }
        public IEnumerable<SelectListItem> Clientes { get; set; }
    }
}

Controllers/ItensPedidoController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.MVC.ComercioDigital.Models;

namespace Web.MVC.ComercioDigital.Controllers
{
    public class ItensPedidoController : Controller
    {
        readonly string apiBaseAddress = ConfigurationManager.AppSettings["EnderecoApi"];

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> NovoItem(string pedidoId)
        {
            IEnumerable<Produto> produtos;
            ItemPedido itemPedido = new ItemPedido();
            itemPedido.PedidoId = new Guid(pedidoId);

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var result = await client.GetAsync("produtos");

                if (result.IsSuccessStatusCode)
                {
                    string conteudoRetorno = await result.Content.ReadAsStringAsync();
                    produtos = JsonConvert.DeserializeObject<List<Produto>>(conteudoRetorno);
                    itemPedido.Produtos = produtos.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Nome });
                }
                else
                {
                    produtos = Enumerable.Empty<Produto>();
                    ModelState.AddModelError(string.Empty, "Erro ao listar produtos.");
                }
            }
            return View(itemPedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NovoItem([Bind(Include = "PedidoId, ProdutoId, Quantidade")] ItemPedido itemPedido)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(itemPedido);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiBaseAddress);
                    var response = await client.PostAsync("itens", data);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("../Pedido/Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erro ao cadastrar item.");
                    }
                }
            }
            return View(itemPedido);
        }

        public async Task<ActionResult> Detalhes(string pedidoId)
        {
            if (pedidoId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            IEnumerable<ItemPedido> itensPedido = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var result = await client.GetAsync($"itens/pedido/{pedidoId}");

                if (result.IsSuccessStatusCode)
                {
                    string conteudoRetorno = await result.Content.ReadAsStringAsync();
                    itensPedido = JsonConvert.DeserializeObject<List<ItemPedido>>(conteudoRetorno);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro ao listar detalhes do pedido.");
                }
            }

            if (itensPedido == null)
            {
                return HttpNotFound();
            }

            return View(itensPedido);
        }

        [HttpGet]
        public async Task<ActionResult> AtualizaItemPedido(string id)
        {
            return await ObterItemPedido(id);
        }

        [HttpGet]
        public async Task<ActionResult> ExcluiItemPedido(string id)
        {
            return await ObterItemPedido(id);
        }

        [HttpPost, ActionName("ExcluiItemPedido")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmarExclusao(string id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var response = await client.DeleteAsync($"itens/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("../Pedido/Index");
                }
                else
                    ModelState.AddModelError(string.Empty, "Erro ao excluir pedido.");
            }
            return View();
        }

        private async Task<ActionResult> ObterItemPedido(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ItemPedido itemPedido = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var result = await client.GetAsync($"itens/{id}");

                if (result.IsSuccessStatusCode)
                {
                    string retorno = await result.Content.ReadAsStringAsync();
                    itemPedido = JsonConvert.DeserializeObject<ItemPedido>(retorno);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro ao obter dados do pedido.");
                }
            }

            if (itemPedido == null)
            {
                return HttpNotFound();
            }

            return View(itemPedido);
        }
    }
}

Controllers/PedidoController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.MVC.ComercioDigital.Models;

namespace Web.MVC.ComercioDigital.Controllers
{
    public class PedidoController : Controller
    {
        readonly string apiBaseAddress = ConfigurationManager.AppSettings["EnderecoApi"];

        public async Task<ActionResult> Index()
        {
            IEnumerable<Pedido> pedidos = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var result = await client.GetAsync("pedidos");

                if (result.IsSuccessStatusCode)
                {
                    string conteudoRetorno = await result.Content.ReadAsStringAsync();
                    pedidos = JsonConvert.DeserializeObject<List<Pedido>>(conteudoRetorno);
                }
                else
                {
                    pedidos = Enumerable.Empty<Pedido>();
                    ModelState.AddModelError(string.Empty, "Erro ao listar pedidos.");
                }
            }
            return View(pedidos);
        }

        public async Task<ActionResult> NovoPedido()
        {
            IEnumerable<Cliente> clientes = null;
            Pedido pedido = new Pedido();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);
                var result = await client.GetAsync("clientes");

                if (result.IsSuccessStatusCode)
                {
                    string retorno = await result.Content.ReadAsStringAsync();
                    clientes = JsonConvert.DeserializeObject<List<Cliente>>(retorno);
                    pedido.Clientes = clientes.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Nome });
                }
                else
                {
                    clientes = Enumerable.Empty<Cliente>();
                    ModelState.AddModelError(string.Empty, "Erro ao listar clientes.");
                }
            }
            
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> NovoPedido([Bind(Include = "Titulo, ClienteId")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(pedido);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiBaseAddress);
                    var response = await client.PostAsync("pedidos", data);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erro ao cadastrar novo pedido.");
                    }
                }
            }
            return View(pedido);
        }

        [HttpGet]
        public async Task<ActionResult> AtualizaPedido(string id)
        {
            return await ObterPedido(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AtualizaPedido([Bind(Include = "Id, Titulo")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(pedido.Titulo);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiBaseAddress);
                    var response = await client.PutAsync($"pedidos/{pedido.Id}", data);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erro ao atualizar dados do pedido.");
                    }
                }
                return RedirectToAction("Index");
            }
            return View(pedido);
        }

        [HttpGet, ActionName("ExcluiPedido")]
        public async Task<ActionResult> ExcluiPedido(string id)
        {
            return await ObterPedido(id);
        }

        [HttpPost, ActionName("ExcluiPedido")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmarExclusao(string id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var response = await client.DeleteAsync($"pedidos/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(string.Empty, "Erro ao excluir pedido.");
            }
            return View();
        }

        private async Task<ActionResult> ObterPedido(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var result = await client.GetAsync($"pedidos/{id}");

                if (result.IsSuccessStatusCode)
                {
                    string retorno = await result.Content.ReadAsStringAsync();
                    pedido = JsonConvert.DeserializeObject<Pedido>(retorno);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro ao obter dados do pedido.");
                }
            }

            if (pedido == null)
            {
                return HttpNotFound();
            }

            return View(pedido);
        }
    }
}

Views/Pedido/AtualizaPedido.cshtml
@model Web.MVC.ComercioDigital.Models.Pedido

@{
    ViewBag.Title = "Editar Pedido";
}

<h2>Editar Informações do Pedido</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Pedido/ExcluiPedido.cshtml
@model Web.MVC.ComercioDigital.Models.Pedido

@{
    ViewBag.Title = "Excluir Pedido";
}

<h3>Excluir Pedido</h3>

<h4>Deseja realmente excluir o pedido?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Views/Pedido/Index.cshtml
@model IEnumerable<Web.MVC.ComercioDigital.Models.Pedido>

@{
    ViewBag.Title = "Pedidos";
}

<h3>Lista de Pedidos</h3>

<p>
    @Html.ActionLink("Adicionar Novo Pedido", "NovoPedido")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeCliente)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.ActionLink(item.Id.ToString(), "Details", new { id = item.Id })*@
                @Html.ActionLink(item.Id.ToString(), "Detalhes", "ItensPedido", new { pedidoId = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCliente)
            </td>
            <td>
                @Html.ActionLink("Incluir Item", "NovoItem", "ItensPedido", new { pedidoId = item.Id }, null) |
                @Html.ActionLink("Alterar", "AtualizaPedido", new { id = item.Id }) |
                @Html.ActionLink("Excluir", "ExcluiPedido", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Views/Pedido/NovoItem.cshtml
@using Web.MVC.ComercioDigital.Models;

@model Web.MVC.ComercioDigital.Models.ItemPedido

@{
    ViewBag.Title = "Novo Item";
}

<h3>Novo Item</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProdutoId, Model.Produtos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Pedido/NovoPedido.cshtml
@using Web.MVC.ComercioDigital.Models;

@model Web.MVC.ComercioDigital.Models.Pedido

@{
    ViewBag.Title = "Novo Pedido";
}

<h3>Novo Pedido</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ClienteId, Model.Clientes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}